### ISSUE TITLE
strings that are invalid SQL variable names cause errors when passed to pyorient.ogm.Batch.__setitem__() 

### ISSUE THREAD

**Issue by lebedov** [mogui/pyorient#137]
Currently (as of 4474709), passing variables containing characters such as hyphens (e.g., 'TX-1') to Batch.\_\_setitem\_\_() when adding nodes/edges to the batch will cause an SQL error during batch execution because the resulting variable names ('$TX-1' in this case) are invalid. At the least, it would be desirable for the method to raise an exception if such strings are passed to it. More sophisticated handling could ensure that all strings specified are encoded to valid SQL variable names.

**Comment by TropicalPenguin** [comment]
Hi @lebedov,

In testing, I found that it is possible to have hyphens in variable names, so long as you either
1) Use them only as a return value
2) Don't use them (...which defeats their purpose).

While I like the idea of warning as early as possible (in __setitem__), I thought it more important to be as faithful as possible to what OrientDB allows, so I've made __getitem__ raise an exception instead.

That is the default behaviour. Calling the classmethod Batch.use_name_cleaner() allows you to provide a function that will return a valid equivalent of the input string. When this is not None (a basic default is provided), these sanitised inputs will be used in the batch command, rather than raising an exception.
