### ISSUE TITLE
Null record support, for the sake of the gremlin 'optional' operator

### ISSUE THREAD

**Issue by obi1kenobi** [mogui/pyorient#150]
Pyorient currently does not support returning records with `null` entries -- it simply raises an `Exception(NULL Record)` in `messages/base.py#_read_record`.

This is very unfortunate, as it renders the [optional](http://gremlindocs.spmallette.documentup.com/#optional) gremlin operator useless -- when the optionally-selected record does not exist, it's returned as `null` and pyorient raises an exception. This is unfortunately not as simple as replacing the line that raises an exception with a line that sets the function result to `None`, even though the pyorient tests pass -- for some reason that I wasn't able to track down, this causes incorrect outputs from my (rather complex) gremlin function.

I'd love to hear your thoughts on the best way to support `null` records, and I'd be willing to contribute code to get this fixed ASAP.

**Comment by neRok-** [comment]
I am experiencing this problem too.

I have attempted to mod pyorient to return None, rather than raise an error. I notice in the query results though, there will be a None, rather than the record I expect. Eg: If I did a query like `select from V`, I would expect the results to be along the lines of `[<oRecord for #9:0>, <oRecord for #9:1>, <oRecord for #9:2>]`, but I actually get `[<oRecord for #9:0>, None, <oRecord for #9:2>]`.

I can reproduce the problem with my database and with a complex query, but I cannot get it to happen on a test database with simple records. The query works fine in the Studio tool though.

I did notice that when the error occurs, an error also appears in the server console along the lines of `WARNI {db=family-tree-disk} Cannot serialize record: Person#12:133{sex:Female,out_Milestone:[#31:201, #31:202, #31:203, #31:204, #31:205, #23:97, #29:11],in_Child:[size=2],out_
Names:[#16:134, #16:135],in_Spouse:[size=1],out_Child:[size=1],$sort:1903P1Y,birth:[1],death:[0],name:[2]} v14 [ONetworkProtocolBinary]`. So in my case something is wrong on OrientDB end that pyorient isn't handling it very well.

Even if my record was serializing properly and I wasn't experiencing this error/exception, obi1kenobi point would still probably remain.

**Comment by neRok-** [comment]
Actually I did manage to replicate the issue with a simple database, however pyorient was throwing a different error in this instance. Anyway, see https://github.com/orientechnologies/orientdb/issues/5579

**Comment by mogui** [comment]
merged in develop
