### ISSUE TITLE
Sockets leak

### ISSUE THREAD

**Issue by spivachuk** [mogui/pyorient#233]
A socket opened in `OrientSocket.__init__` method is replaced for nothing with a new one in `OrientSocket.connect` method. So the socket opened in `OrientSocket.__init__` is wasted and remains unclosed.
Moreover, in `OrientDB` class there is no way to close underlying `OrientSocket` (it is only closed in case of some error).

**Comment by spivachuk** [comment]
Created the fix for this issue:
https://github.com/mogui/pyorient/pull/234

**Comment by anber500** [comment]
I'm excited by this fix. This could potentially fix all my OrientDB issues. I'm using pyorient with celery and rabbitmq. We could not run celery with more than 1 worker because for some reason OrientDB would go ape-shit if we did and start locking the records and not release them. I initially suspected celery was not closing the connections and flooding OrientDB's connection pool. 

We found that in distributed mode, when using celery, OrientDB would struggle with concurrency.

Could this fix point to the illusive double connection we've been experiencing?

**Comment by spivachuk** [comment]
@anber500, the PR #234 eliminates the redundant double connection which leaded to sockets leak. Also `close` method is added to `OrientDB` class. It should be called when the `OrientDB` class instance is not needed anymore in order to close the underlying socket.

**Comment by spivachuk** [comment]
Create a PR with the same fix as in #234 but for `master` branch:
#235

**Comment by spivachuk** [comment]
@TropicalPenguin, when is it planned to merge recent changes from develop to master and release the next version?

**Comment by TropicalPenguin** [comment]
I'd imagine fairly promptly after the following unit tests are passing again for the develop branch:

```
tests.test_Factory_and_usage.CommandTestCase
tests.test_new_Iface.CommandTestCase
tests.test_raw_messages_3.RawMessages_5_TestCase
```
Unfortunately I'm not familiar with the area of the code covered by these. I suspect if anyone is to fix them, it would then be a trivial decision for @mogui to merge to master and do a new release.

**Comment by Ostico** [comment]
Hi all,
i'm checking for tests failures, these failures could be related with some internal changes in OrientDB and the tests must be changed accordingly.

@anber500 as @spivachuk said this only remove a redundant initialization. Probably you have to close the no more used sockets by yourself.

Tnx @spivachuk for your PR, the close method will be useful.

**Comment by Ostico** [comment]
The failures

**Comment by Ostico** [comment]
Merged
