### ISSUE TITLE
Is OrientRecordLink.get_hash intentionally returning double-hashes?

### ISSUE THREAD

**Issue by TropicalPenguin** [mogui/pyorient#242]
I don't know if this an artifact of newer OrientDB releases, but at least for 2.2.18 get_hash is returning a string with two leading '#'s.

Is this intentional? Or could some sanitising be done so that the string returned by `__str__()` can be used in queries?

To reproduce:
```
from pyorient.ogm.declarative import declarative_node
 
Node = declarative_node()
 
class Foo(Node):
    element_plural = 'foos'
 
from pyorient.ogm import Graph, Config
 
g = Graph(Config.from_url('test', 'root', 'root', initial_drop=True))
g.create_all(Node.registry)
 
b = g.batch()
 
b['foo'] = b.foos.create()
b['rid'] = b[:'foo'].at_rid()
# An OrientRecordLink
rid = b['$rid']
 
print(rid)
```

**Comment by nikulukani** [comment]
This is happening due to https://github.com/mogui/pyorient/blob/develop/pyorient/messages/base.py#L388

The _decode_field function prepends a "#" when called with FIELD_TYPE_LINK, which happens when the only thing returned from a command is an rid.

This is then used to initialize OrientRecordLink which expects a string representing rid without the preceding "#".

As the only place _decode_field is called with FIELD_TYPE_LINK is https://github.com/mogui/pyorient/blob/develop/pyorient/messages/base.py#L467, I suggest changing it so that it does not prepend "#"

**Comment by TropicalPenguin** [comment]
Done, thanks!
