### ISSUE TITLE
Pyorient won't unlock database

### ISSUE THREAD

**Issue by ysimonson** [mogui/pyorient#54]
Hi, I'm trying to use pyorient to create a database, but it doesn't seem to unlock the database afterwards.

With the environment variable `ODB_URL=orientdb://root:foo@localhost:2424/test`, I'll run this script:

    #!/usr/bin/env python

    import os
    import pyorient
    import urllib.parse

    def main():
        print(os.environ["ODB_URL"])
        parsed = urllib.parse.urlparse(os.environ["ODB_URL"])
        conn = pyorient.OrientDB(parsed.hostname, parsed.port)
        conn.connect(parsed.username, parsed.password)
        conn.db_create(parsed.path[1:], pyorient.DB_TYPE_GRAPH, pyorient.STORAGE_TYPE_PLOCAL)
        conn.db_close()

    if __name__ == "__main__":
        main()

The process exits normally. Everything appears fine until using OrientDB's `console.sh` afterwards, which gives this error:

	orientdb>  connect plocal:/home/vagrant/orientdb/databases/test root foo;

	Connecting to database [plocal:/home/vagrant/orientdb/databases/test] with user 'root'...
	Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/vagrant/orientdb/databases/test' with mode=rw

	Error: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.

	Error: com.orientechnologies.common.concur.lock.OLockException: File '/home/vagrant/orientdb/databases/test/database.ocf' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database.

**Comment by Ostico** [comment]
Hi @ysimonson , 
i tried your script and you're right, but this is not a pyorient fault, you should open an issue to Orient Db.

In my OrientDB logs i found this when the driver performs a close db:
```
2015-03-23 01:00:23:121 INFO  /127.0.0.1:40089 - Reading byte (1 byte)... [OChannelBinaryServer]
2015-03-23 01:00:26:647 INFO  /127.0.0.1:40089 - Read byte: 5 [OChannelBinaryServer]
2015-03-23 01:00:26:648 INFO  /127.0.0.1:40089 - Reading int (4 bytes)... [OChannelBinaryServer]
2015-03-23 01:00:26:648 INFO  /127.0.0.1:40089 - Read int: 4 [OChannelBinaryServer]
2015-03-23 01:00:26:649 INFO  /127.0.0.1:40089 - Reading byte (1 byte)... [OChannelBinaryServer]
2015-03-23 01:00:26:664 INFO  /127.0.0.1:40089 - Flush [OChannelBinaryServer]
2015-03-23 01:00:26:664 INFO  /127.0.0.1:40089 - Closing socket... [OChannelBinaryServer]
```

So, OrientDB close the socket by your side as the specification says:
[http://www.orientechnologies.com/docs/last/orientdb.wiki/Network-Binary-Protocol.html#request_db_close](http://www.orientechnologies.com/docs/last/orientdb.wiki/Network-Binary-Protocol.html#request_db_close)

By the way, the exception you noticed did not happen if you try to connect with the remote protocol by the console:
```
orientdb> connect remote:127.0.0.1/test admin admin
Connecting to database [remote:127.0.0.1/test] with user 'admin'...OK
orientdb {db=test}> select from V

0 item(s) found. Query executed in 0.007 sec(s).
orientdb {db=test}>
```

My hypothesis ( but i should ask to Orient Team ):
i think this happens because the binary protocol is not a local protocol by design, so creating a new db from a remote connection, in some manner locks the resource and accessing that resource by local console is no more possible ( ? ).

**Comment by ysimonson** [comment]
OK, thank you for investigating
