### ISSUE TITLE
client.command("select * from V") does not return all fields

### ISSUE THREAD

**Issue by rwnew2012** [mogui/pyorient#66]
I might missed something obviously, but when I want to query the database
res = client.command("select * from V ")
res[0].oRecordData.keys()

it does not return all fields, looks like fields are chosen randomly. Is this a issue for pyorient, or I need specify something to have all fields returns.Thanks!

**Comment by sinfex** [comment]
Could you specify the output and point out what seems to be random?

Are you asking why certain records have fields that others don't? If so...

\# **shorter explanation below**

**V** is the root vertex class. By performing `SELECT FROM V` you are selecting all vertices stored in the database, i.e. vertices of any class.
Each class is most likely to have different fields defined as part of the schema. OrientDB can operate in a schema-less mode, which means that fields can be removed/added to particular records without having to do so to all records of the same class.

Let's say you have A and B, both are vertex subclasses of V. Try the following in the OrientDB Console:
```
CREATE CLASS A EXTENDS V
CREATE CLASS B EXTENDS V
CREATE VERTEX A SET field1 = 1
CREATE VERTEX B SET field2 = 2
SELECT FROM V
```

Example output:
```
----+-----+------+------+----
#   |@RID |@CLASS|field1|field2
----+-----+------+------+----
0   |#21:0|A     |1     |null
1   |#22:0|B     |null  |2
----+-----+------+------+----
```

\# **tl;dr**

Since the records have fields that other are *"missing"*, Studio displays NULL simply to maintain a nice table structure - as you can see from the example, no NULL values are really being stored. i.e. in the example above, the key *field2* will be missing in the first record returned by pyorient.

**Comment by blackhathedgehog** [comment]
It could be because of: 

https://github.com/mogui/pyorient/pull/75

**Comment by Ostico** [comment]
Seems resolved, reopen if needed.
