### ISSUE TITLE
Why is record id a protected member?

### ISSUE THREAD

**Issue by dargolith** [mogui/pyorient#69]
With an OrientRecord object there's some properties, one being _rid (for record id) which by convention are marked as protected members.

Either I have misunderstood it and _rid should not be used externally. If so I would like another way to get the record id of a returned OrientRecord. Otherwise I would like the property to not be marked as protected, ie without leading underscore (_rid -> rid). I noticed this applies for more properties as well.

It's still possible to use protected members in python where they shouldn't be used, but inspection complains about it and it is also not encouraged.

Thanks for making a python binding for an awesome database!

**Comment by neRok-** [comment]
The attribute 'in' was renamed to '_in' as part of issue https://github.com/mogui/pyorient/issues/22 , so that it wouldn't conflict with the in operator. My guess is the 'rid' and 'class' attributes (maybe more) were then renamed to '\_rid' and '\_class' to keep the naming convention the same.

Using a trailing underscore is the norm to prevent conflicts with python keywords, thus '\_in' should probably be 'in\_'. However, 'rid\_' seems a bit pointless, so maybe it should be returned to 'rid'. Naming it '@rid' as OrientDB uses wont work either.

**Comment by Ostico** [comment]
Hi @dargolith ,
@neRok- is right.

Please refer to [https://github.com/mogui/pyorient/issues/4](https://github.com/mogui/pyorient/issues/41).

Moreover i can't use in_ , out_ because OrientDB use them as default edge names in vertex class V

**Comment by dargolith** [comment]
I thought I had answered this, apparently not.

Thanks for the answers. Perhaps there's some naming that can be used in the future to avoid this. It would be nice to stick to conventions. At least I know for now that there's no problem to just suppress those inspection errors and use the protected members as public.
