### ISSUE TITLE
record_create() not honoring given clusterID

### ISSUE THREAD

**Issue by mcaramma** [mogui/pyorient#76]
During development I found all created objects rid always match #3:[pos] no matter which cluster_id number is passed as argument during record_create(cluster_id, data) call.

To fix this and honor cluster_id argument pyorient/messages/commands.py(445)

     ( FIELD_SHORT, int(-1) ),

shuld be modified to

     ( FIELD_SHORT, int(getattr(operation, "_cluster_id")) ),

Thanks

**Comment by Ostico** [comment]
Hi @mcaramma ,

the code you reported as wrong, refers to the transactions and not to the creation of simple objects in **record_create** method call. I think it is right.
Can you provide me a simple piece of code to reproduce your issue and the expected behaviour?
 I will try to find the issue and to fix it.

Tnx

**Comment by Ostico** [comment]
No answer, i close.
