### ISSUE TITLE
db_open with a username/password that differs from that of the server prevents one from running db_list

### ISSUE THREAD

**Issue by lebedov** [mogui/pyorient#82]
Using revision 7254679 of pyorient with OrientDB Community 2.0.12 on Ubuntu 14.04.2, I noticed that opening a database with a username/password that differ from that of the server causes subsequent invocations of client.db_list to fail:

```
import pyorient
client = pyorient.OrientDB('localhost', 2424)
client.connect('username', 'passwd')
client.db_open('temp', 'admin', 'admin')

# The following throws an exception:
print client.db_list()
```

**Comment by Ostico** [comment]
Hi @lebedov ,

this is because the user needed to run database administration ( CONNNECT ) commands differs from the privilege/users used to open a database ( DB_OPEN ) and perform data manipulations.

https://orientdb.com/docs/last/Network-Binary-Protocol.html#operation-types

So to have a list of databases you must connect with ```'username' and 'password'``` and after, when you choosed a database you can connect with ```'admin', 'admin' ```.

So try this:
```python
import pyorient
client = pyorient.OrientDB('localhost', 2424)
client.connect('username', 'passwd')
print client.db_list()

client.db_open('temp', 'admin', 'admin')
```
